### ISSUE TITLE
Cambio de color en fondos

### ISSUE THREAD

**Issue by Fransouls** [rtorralba/zx-game-maker-skeleton#15]
Que sea posible en un futuro poder añadir nuevos colores de fondo, no se si es posible ya cambiando el primer tile de color y si es así los personajes fuesen en negro para ser diferenciados sin problemas.

**Comment by rtorralba** [comment]
En la redacción de esta issue hay varias funcionalidades en una, la posibilidad de cambiar el fondo ya está disponible de hace un tiempo, te dejo la documentación.

https://gm.retrojuegos.org/mydoc_tiled_general_configuration.html
