### ISSUE TITLE
codigo fuente del motor

### ISSUE THREAD

**Issue by raulgarfer** [rtorralba/zx-game-maker-skeleton#17]
¿Sería posible heacer público el código fuente de motor?
Según esté implementado, se pueden dar ideas de como avanzar 
o a grandes rasgos, como está hecho.
un saludo

**Comment by rtorralba** [comment]
Si alguien está interesado en colaborar solo tiene que decirlo y le daré permiso para acceder, seguramente lo liberaré cuando salga de la beta.
