### ISSUE TITLE
ejecutar emulador en script

### ISSUE THREAD

**Issue by raulgarfer** [rtorralba/zx-game-maker-skeleton#2]
no se si seria bueno añadir al final que se lance el emulador y ejecute el juego, despues de haber compilado
un saludo

**Comment by rtorralba** [comment]
Esto es complicado porque cada uno tiene un sistema operativo y un emulador, yo simplemente ejecuto fuse assets/game.tap que incluso te puedes hacer un script con esa orden o el emulador que prefieras en el sistema operativo que uses
