### ISSUE TITLE
Autoloop de música

### ISSUE THREAD

**Issue by ZXKerl** [rtorralba/zx-game-maker-skeleton#25]
Activado el loop en Vortex tracker y no funciona en el juego. No se reinicia la musica al terminar la canción.

**Comment by rtorralba** [comment]
Acabo de probar una música con loop y funciona perfectamente

**Comment by ZXKerl** [comment]
OK. No estoy seguro pero supongo que habrá que añadir el loop desde el tracker, guardar como pt3 y repetir los pasos del export.
