### ISSUE TITLE
Disminuir el tiempo de invencibilidad

### ISSUE THREAD

**Issue by ZXKerl** [rtorralba/zx-game-maker-skeleton#27]
Disminuir el tiempo de invencibilidad para equilibrar el juego y no otorgar demasiada ventaja a los enemigos.

**Comment by rtorralba** [comment]
Esto ya lo hice hace tiempo, si todavía lo ves demasiado alto comentamelo, sino cierra la issue como realizada please.

**Comment by ZXKerl** [comment]
Cerrada como realizada. Gracias.
