### ISSUE TITLE
Kempston

### ISSUE THREAD

**Issue by ZXKerl** [rtorralba/zx-game-maker-skeleton#28]
I couldn't get the kempston option to work. It responds, but your character hops around randomly and the controls move him around unpredictably. This was using SpecEmu emulator.

I tried 128k mode in SpecEmu and it worked fine. It also worked fine in 128k mode using Spectaculator and RVM emulator. However, on Spectaculator in 128k mode, when you select Kempston, it crashes as soon as the first screen is displayed.

**Comment by rtorralba** [comment]
Fixed and tested with fuse with joystick and rmv mapping to cursors
