### ISSUE TITLE
Memoria llena

### ISSUE THREAD

**Issue by Fransouls** [rtorralba/zx-game-maker-skeleton#3]
Es posible que necesite comprimir los datos de los mapas, puesto que con 6 pantallas con tiles y 6 en negro la memoria queda llena.

**Comment by rtorralba** [comment]
Se pueden aproximadamente 40 pantallas y seguramente con próximas actualizaciones se podrán más, cuando las funcionalidades básicas estén terminadas daremos varias vueltas de optimización.

**Comment by Fransouls** [comment]
________________________________
De: rtorralba ***@***.***>
Enviado: domingo, 26 de noviembre de 2023 11:50
Para: rtorralba/zx-game-maker-skeleton ***@***.***>
Cc: Fransouls ***@***.***>; Author ***@***.***>
Asunto: Re: [rtorralba/zx-game-maker-skeleton] Memoria llena (Issue #3)


Se pueden aproximadamente 40 pantallas y seguramente con próximas actualizaciones se podrán más, cuando las funcionalidades básicas estén terminadas daremos varias vueltas de optimización.
