### ISSUE TITLE
No se muestra disparo (de distancia 1) cuando el prota mira a la derecha

### ISSUE THREAD

**Issue by cperezgrin** [rtorralba/zx-game-maker-skeleton#43]
Para un disparo de distancia 1, no se dibuja cuando el prota mira a la derecha. Seguramente será sólo añadir un desplazamiento (el ancho del prota)

**Comment by rtorralba** [comment]
fixed

![Peek 2024-04-18 18-43](https://github.com/rtorralba/zx-game-maker-skeleton/assets/3964372/416878b9-e643-46d8-9105-e996b873476f)
