### ISSUE TITLE
Fallo controlador kempstom 

### ISSUE THREAD

**Issue by Fransouls77** [rtorralba/zx-game-maker-skeleton#46]
Revisar controlador kempstom por fallo en posibles emuladores.

**Comment by rtorralba** [comment]
He probado tanto en retro virtual machine como en fuse y funciona perfectamente

**Comment by Fransouls77** [comment]
Gracias, parece ser que es si no conectas el joystick con el emulador fuse

**Comment by Fransouls77** [comment]
Ok gracias!!
