### ISSUE TITLE
El mapa del skeleton tiene tiles "fantasma"

### ISSUE THREAD

**Issue by adeluiz** [rtorralba/zx-game-maker-skeleton#47]
Buenas, como la gente va a usar el maps.tmx como base de su juego, encuentro incómodo que se encuentren tiles invisibles (sobre todo los sólidos). 

Al detectar comportamientos extraños del personaje coloreé los tiles vacíos y me encontré con que había tiles sin contenido pero algunos incluso se consideraban sólidos. Adjunto captura de los tiles y del mapa. Gracias!

![tiles](https://github.com/rtorralba/zx-game-maker-skeleton/assets/4427432/7dbaf4db-1e23-40d0-89fa-230fafb41fc9)

![mapa](https://github.com/rtorralba/zx-game-maker-skeleton/assets/4427432/da0c47fb-b83a-4d09-803c-f8a705b2f50c)

**Comment by rtorralba** [comment]
El skeleton es solo un ejemplo basta con pintar encima, pero ya lo he arreglado
