### ISSUE TITLE
Velocidad de frames

### ISSUE THREAD

**Issue by Fransouls77** [rtorralba/zx-game-maker-skeleton#49]
Reducir la velocidad frames del héroe que es demasiado rapida y acelerar un poco la de los enemigos que va muy lenta.

**Comment by rtorralba** [comment]
Arreglado y además ahora puedes moderar o acelerar la velocidad de las animaciones con los siguientes atributos

animatePeriodMain
animatePeriodEnemy
animatePeriodTile

Este valor es cada cuantos ciclos se cambia a otro frame, es decir, a valores más altos se animará más lento.

Pruébalo y si te funciona bien cierra la issue please.

![image](https://github.com/rtorralba/zx-game-maker-skeleton/assets/3964372/bea20f50-4f30-430b-9cbb-be982f3af38b)

**Comment by rubencougil** [comment]
Lo acabo de probar para "animatePeriodMain" y fuciona 👍

**Comment by Fransouls77** [comment]
Gracias mañana lo miro
