### ISSUE TITLE
[Error] Se dibuja el sprite sobre el marcador.

### ISSUE THREAD

**Issue by Andress72** [rtorralba/zx-game-maker-skeleton#54]
Cuando se está bajando a una pantalla inferior y se presiona la tecla A o abajo en el joystick, la parte inferior del sprite se queda dibujada sobre el marcador. Es con el joystick cómo me ocurre más frecuentemente, ya que de forma involuntaria  le suelo dar abajo o en diagonal abajo cuando salto hacia una pantalla inferior. Con las teclas es más difícil que ocurra, más que nada porque no se pulsa la A.

![6Z6KGa](https://github.com/rtorralba/zx-game-maker-skeleton/assets/174233954/85d42cbf-50c2-4cf2-a4ca-47fb7134faa0)
![MLlig+](https://github.com/rtorralba/zx-game-maker-skeleton/assets/174233954/b0aeef7e-a09b-4621-a980-8057dd05432e)

**Comment by rtorralba** [comment]
@Andress72 ya debería estar arreglado, pero tienes que probarlo en una compilación nueva, los que ya están compilados continuarán con el error (como es obvio), si lo ves OK avisame y cierro la issue.

Muchas gracias!

**Comment by Andress72** [comment]
Gracias. Aunque no lo puedo comprobar ya que no soy desarrollador, pero cierro la issue entonces.
