### ISSUE TITLE
(BUG) Proyectil fantasma en bucle

### ISSUE THREAD

**Issue by sirsercas** [rtorralba/zx-game-maker-skeleton#58]
Buenos días,

Este error se produjo en el juego que estoy haciendo. Para asegurarme que no era porque yo hubiera hecho algo raro, lo he reproducido con la última versión del _Skeleton_, como se puede observar en el _.tzx_ que adjunto dentro de _proyectil_fantasma.zip_ (no deja enviar _.tzx_).

Estoy usando la última versión, la que se puede matar enemigos saltando encima, etc. En mi juego (vista lateral), el héroe es un paladín con arma de cuerpo a cuerpo, un martillo. Para poder hacer esto, los únicos atributos que he modificado son:

· ammno --> -1 (para que no haya que recargarla, un arma de cuerpo a cuerpo es 'infinita')
· bulletDistance --> 2 (es el alcance óptimo para este tipo de arma)

El error se produce al entrar en la segunda pantalla del _Skeleton_ (y en mi juego) y disparar al soldado imperial. El proyectil adquiere un comportamiento anómalo, persiguiendo al héroe hasta alcanzarlo, para, seguidamente, volver al inicio de la pantalla y recorrerla de nuevo hasta  volver a alcanzarlo, una y otra vez. Hasta al infinito o hasta que, por casualidad, impacte al soldado imperial, si nos movemos de posición.

Llevo un tiempo haciendo mi juego y con la versión anterior no ocurría este fallo. Ha sido al descargar la última versión del _Skeleton_ con las nuevas mejoras.

Por otro lado, haciendo sólo estos dos cambios en los atributos del _Tiled_ (munición infinita [-1] y un alcance distinto del máximo [0]) en la última versión del _Skeleton_ (recién descargada y sin tocar nada de nada más), se queda sin memoria y da error de compilación. Para poder hacer que compile, he tenido que deshabilitar la música. Por ahora me sirve para seguir avanzando con mi juego, pero a la larga mi intención es ponerle música.

Quedo a tu disposición para aclarar cualquier duda y colaborar en lo que haga falta.
Gracias por el motor.

[proyectil_fantasma.zip](https://github.com/user-attachments/files/17326415/proyectil_fantasma.zip)

**Comment by rtorralba** [comment]
Gracias por reportar! Arreglado!

Lo otro que comentas mejor por el grupo de telegram que hay que comentarlo en detalle. Intenta centrar las issues en una cosa, si ves cosas distintas distintas issues.

Gracias!

**Comment by sirsercas** [comment]
Un placer :)
